/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as InterviewClientIdRouteImport } from './routes/interview-client.$id'
import { Route as AdminQuestionnairesRouteImport } from './routes/admin/questionnaires'
import { Route as AdminFeedbacksRouteImport } from './routes/admin/feedbacks'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const InterviewClientIdRoute = InterviewClientIdRouteImport.update({
  id: '/interview-client/$id',
  path: '/interview-client/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminQuestionnairesRoute = AdminQuestionnairesRouteImport.update({
  id: '/admin/questionnaires',
  path: '/admin/questionnaires',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminFeedbacksRoute = AdminFeedbacksRouteImport.update({
  id: '/admin/feedbacks',
  path: '/admin/feedbacks',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin/feedbacks': typeof AdminFeedbacksRoute
  '/admin/questionnaires': typeof AdminQuestionnairesRoute
  '/interview-client/$id': typeof InterviewClientIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin/feedbacks': typeof AdminFeedbacksRoute
  '/admin/questionnaires': typeof AdminQuestionnairesRoute
  '/interview-client/$id': typeof InterviewClientIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin/feedbacks': typeof AdminFeedbacksRoute
  '/admin/questionnaires': typeof AdminQuestionnairesRoute
  '/interview-client/$id': typeof InterviewClientIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin/feedbacks'
    | '/admin/questionnaires'
    | '/interview-client/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin/feedbacks'
    | '/admin/questionnaires'
    | '/interview-client/$id'
  id:
    | '__root__'
    | '/'
    | '/admin/feedbacks'
    | '/admin/questionnaires'
    | '/interview-client/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminFeedbacksRoute: typeof AdminFeedbacksRoute
  AdminQuestionnairesRoute: typeof AdminQuestionnairesRoute
  InterviewClientIdRoute: typeof InterviewClientIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/interview-client/$id': {
      id: '/interview-client/$id'
      path: '/interview-client/$id'
      fullPath: '/interview-client/$id'
      preLoaderRoute: typeof InterviewClientIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/questionnaires': {
      id: '/admin/questionnaires'
      path: '/admin/questionnaires'
      fullPath: '/admin/questionnaires'
      preLoaderRoute: typeof AdminQuestionnairesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/feedbacks': {
      id: '/admin/feedbacks'
      path: '/admin/feedbacks'
      fullPath: '/admin/feedbacks'
      preLoaderRoute: typeof AdminFeedbacksRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminFeedbacksRoute: AdminFeedbacksRoute,
  AdminQuestionnairesRoute: AdminQuestionnairesRoute,
  InterviewClientIdRoute: InterviewClientIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
